version: "2"
linters:
  default: all
  disable:
    # impact=high
    # forcetypeassert: prevent panic on typecast failures
    # gci, gofumpt, goimports: formats much better than go fmt
    # gosec: usually catches big bugs, but has false positives
    # nilnil: return nil, nil, usually err=nil means the value is present
    #
    # impact=dev-experience
    # nonamedreturns, nakedret: it is discouraged to use named returns
    # predeclared: eg param new has same name as predeclared identifier (new cannot be called to allocate in the function)
    # unconvert: explicit conversion is not needed
    # whitespace: gci will fix this
    #
    # to-be-discussed:
    # golint, revive: capitalization mainly - struct field `TokenUrl` should be `TokenURL`
    # errorlint, goerr113, wrapcheck: error wrapping, dynamic errors - very lenghty topic
    # errname: should conform to the `ErrXxx` format
    # funcorder: expect exported method to be defined before unexported
    # paralleltest : expect the whole test suite to be parallelizable. this means very good tests, but a lot of work
    #
    # disabled for good :
    # ireturn: return concrete type, not the interface it implements
    # depguard: limit what can be imported using config file

    - copyloopvar
    - depguard
    - err113
    - errname
    - exhaustive
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funcorder
    - gochecknoglobals
    - gochecknoinits
    - godot
    - godox
    - gosec
    - inamedparam
    - intrange
    - ireturn
    - lll
    - mnd
    - nilnil
    - nlreturn
    - noctx
    - nonamedreturns
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - revive
    - tagalign
    - testpackage
    - unconvert
    - varnamelen
    - whitespace
    - wrapcheck
    - wsl
    - wsl_v5
    - noinlineerr
  settings:
    cyclop:
      max-complexity: 30
    funlen:
      lines: 150
      statements: 120
    gocognit:
      min-complexity: 30
    goconst:
      min-occurrences: 10
    iface:
      enable:
        - identical
        - unused
        - opaque
    maintidx:
      under: 15
    nestif:
      min-complexity: 12
    staticcheck:
      checks:
        # disabled:
        # ST1001: should not use dot imports (ginkgo tests needs it)
        # ST1003 : acronym variables capitalized, eg crdJson should be crdJSON
        - all
        - -ST1001
        - -ST1003
        - -QF*
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - blank
        - dot
        - prefix(github.com/camunda)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
